"""empty message

Revision ID: 9c4b53e06c1c
Revises: ffdc0a98111c
Create Date: 2021-02-22 11:21:56.916179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4b53e06c1c'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posterId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('image', sa.String(length=2000), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('catName', sa.String(length=50), nullable=False),
    sa.Column('startsAt', sa.Date(), nullable=False),
    sa.Column('endsAt', sa.Date(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['posterId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claimStatus',
    sa.Column('claimUserId', sa.Integer(), nullable=False),
    sa.Column('claimedResourceId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claimUserId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['claimedResourceId'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('claimUserId', 'claimedResourceId')
    )
    op.add_column('users', sa.Column('firstname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('isOrg', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('phonenumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phonenumber')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'isOrg')
    op.drop_column('users', 'firstname')
    op.drop_table('claimStatus')
    op.drop_table('resources')
    op.drop_table('locations')
    # ### end Alembic commands ###
